// src/pages/ProductOverview.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Heart, Minus, Plus, Share2, Star } from 'lucide-react'
import { toast } from 'sonner'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ProductImage } from '@/components/ProductImage'
import { getProductById } from '@/lib/api'
import { formatLKR } from '@/lib/format'
import { cn } from '@/lib/utils'
import { useAsync } from '@/hooks/useAsync'
import { useCartStore } from '@/store/cart'
import type { Size } from '@/types'

export default function ProductOverview() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const addToCart = useCartStore((state) => state.addToCart)

  const { data: product, loading } = useAsync(() => getProductById(id ?? ''), [id])

  const [selectedImage, setSelectedImage] = useState<string>()
  const [selectedColor, setSelectedColor] = useState<string>()
  const [selectedSize, setSelectedSize] = useState<Size>()
  const [quantity, setQuantity] = useState(1)
  const [isFavorite, setIsFavorite] = useState(false)

  // Seed the selections from the product once it resolves, as ngOnInit did.
  useEffect(() => {
    if (!product) return
    setSelectedImage(product.image)
    setSelectedColor(product.colors?.[0])
    setSelectedSize(product.sizes?.[0])
    setQuantity(1)
  }, [product])

  if (loading) {
    return (
      <div className="grid gap-6 lg:grid-cols-2">
        <Skeleton className="h-[450px] rounded-xl" />
        <div className="space-y-4">
          <Skeleton className="h-10 w-3/4" />
          <Skeleton className="h-6 w-1/2" />
          <Skeleton className="h-32 w-full" />
        </div>
      </div>
    )
  }

  if (!product) {
    return (
      <div className="py-24 text-center">
        <h1 className="text-2xl font-bold">Product not found</h1>
        <p className="text-muted-foreground mt-2">
          We couldn&apos;t find a product with the id &ldquo;{id}&rdquo;.
        </p>
        <Button className="mt-6" onClick={() => navigate('/product-grid')}>
          Browse products
        </Button>
      </div>
    )
  }

  const share = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href)
      toast.success('Product URL copied to clipboard!')
    } catch {
      toast.error('Failed to copy URL.')
    }
  }

  const handleAddToCart = () => {
    if (product.colors?.length && !selectedColor) {
      toast.warning('Please select a color.')
      return
    }
    if (product.sizes?.length && !selectedSize) {
      toast.warning('Please select a size.')
      return
    }
    if (quantity <= 0) {
      toast.warning('Please select a valid quantity.')
      return
    }

    addToCart({
      product: {
        id: product.id,
        title: product.title,
        price: product.price,
        image: product.image,
      },
      color: selectedColor ?? '',
      size: selectedSize ?? { name: '', description: '' },
      quantity,
    })
    toast.success('Product added to cart successfully!')
  }

  const gallery = product.images?.length ? product.images : [product.image]

  return (
    <div className="space-y-10">
      <section className="grid gap-8 lg:grid-cols-2">
        <div>
          <div className="bg-muted/30 overflow-hidden rounded-xl border">
            <ProductImage
              src={selectedImage ?? product.image}
              alt={product.title}
              className="h-[450px] w-full object-contain"
            />
          </div>
          {gallery.length > 1 && (
            <ul className="mt-3 flex flex-wrap gap-3">
              {gallery.map((image, i) => (
                <li key={`${image}-${i}`}>
                  <button
                    type="button"
                    onClick={() => setSelectedImage(image)}
                    aria-label={`View image ${i + 1}`}
                    aria-current={selectedImage === image}
                    className={cn(
                      'overflow-hidden rounded-xl border-2 transition-colors',
                      selectedImage === image ? 'border-primary' : 'border-transparent',
                    )}
                  >
                    <ProductImage
                      src={image}
                      alt={`${product.title} thumbnail ${i + 1}`}
                      className="size-24 object-contain"
                    />
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div>
          <h1 className="text-primary mb-4 text-3xl leading-tight font-medium md:text-4xl">
            {product.title}
          </h1>

          <div className="text-muted-foreground mb-6 flex flex-wrap items-center gap-2 text-sm">
            {product.rating != null && (
              <span className="flex items-center gap-1">
                <Star className="size-4 fill-yellow-500 text-yellow-500" aria-hidden="true" />
                {product.rating}
              </span>
            )}
            {product.reviewCount != null && <span>· {product.reviewCount} Reviews</span>}
            {product.orderCount != null && <span>· {product.orderCount} Orders</span>}
          </div>

          <p className="text-primary mb-8 text-2xl font-semibold">{formatLKR(product.price)}</p>

          {product.colors?.length ? (
            <fieldset className="mb-6">
              <legend className="mb-2 font-medium">
                Color: <span className="text-muted-foreground">{selectedColor}</span>
              </legend>
              <div className="flex flex-wrap gap-2">
                {product.colors.map((color) => (
                  <button
                    key={color}
                    type="button"
                    onClick={() => setSelectedColor(color)}
                    aria-pressed={selectedColor === color}
                    className={cn(
                      'rounded-md border-2 px-3 py-1.5 text-sm transition-colors',
                      selectedColor === color
                        ? 'border-primary text-primary'
                        : 'border-input hover:border-primary/50',
                    )}
                  >
                    {color}
                  </button>
                ))}
              </div>
            </fieldset>
          ) : null}

          {product.sizes?.length ? (
            <fieldset className="mb-6">
              <legend className="mb-2 font-medium">
                Size: <span className="text-muted-foreground">{selectedSize?.name}</span>
              </legend>
              <div className="flex flex-wrap gap-2">
                {product.sizes.map((size) => (
                  <button
                    key={size.name}
                    type="button"
                    onClick={() => setSelectedSize(size)}
                    aria-pressed={selectedSize?.name === size.name}
                    className={cn(
                      'flex max-w-56 flex-col rounded-md border-2 px-4 py-3 text-left transition-colors',
                      selectedSize?.name === size.name
                        ? 'border-primary'
                        : 'border-input hover:border-primary/50',
                    )}
                  >
                    <b>{size.name}</b>
                    <span className="text-muted-foreground text-sm">{size.description}</span>
                  </button>
                ))}
              </div>
            </fieldset>
          ) : null}

          <div className="mb-6">
            <h2 className="mb-2 font-medium">Quantity</h2>
            <div className="flex w-36 items-center rounded-full border">
              <Button
                variant="ghost"
                size="icon"
                className="rounded-l-full"
                onClick={() => setQuantity((q) => Math.max(1, q - 1))}
                disabled={quantity <= 1}
                aria-label="Decrease quantity"
              >
                <Minus className="size-4" />
              </Button>
              <Input
                type="number"
                min={1}
                value={quantity}
                onChange={(event) => setQuantity(Math.max(1, Number(event.target.value) || 1))}
                aria-label="Quantity"
                className="h-9 border-0 text-center shadow-none focus-visible:ring-0"
              />
              <Button
                variant="ghost"
                size="icon"
                className="rounded-r-full"
                onClick={() => setQuantity((q) => q + 1)}
                aria-label="Increase quantity"
              >
                <Plus className="size-4" />
              </Button>
            </div>
          </div>

          <div className="mb-7 flex flex-wrap items-center gap-2">
            <Button
              onClick={() => {
                handleAddToCart()
                navigate('/checkout')
              }}
              className="uppercase"
            >
              Buy now
            </Button>
            <Button variant="outline" onClick={handleAddToCart} className="uppercase">
              Add to cart
            </Button>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setIsFavorite((value) => !value)}
              aria-pressed={isFavorite}
              aria-label={isFavorite ? 'Remove from favourites' : 'Add to favourites'}
            >
              <Heart className={cn('size-5', isFavorite && 'fill-primary text-primary')} />
            </Button>
            <Button variant="ghost" size="icon" onClick={share} aria-label="Share product">
              <Share2 className="size-5" />
            </Button>
          </div>

          {product.description && (
            <p className="text-muted-foreground">{product.description}</p>
          )}
        </div>
      </section>

      <Card>
        <CardContent>
          <Tabs defaultValue="specifications">
            <TabsList className="w-full">
              <TabsTrigger value="specifications">Specifications</TabsTrigger>
              <TabsTrigger value="comments">Comments</TabsTrigger>
              <TabsTrigger value="files">Files</TabsTrigger>
              <TabsTrigger value="faq">FAQ</TabsTrigger>
            </TabsList>

            <TabsContent value="specifications" className="pt-6">
              {product.specifications?.length ? (
                <dl className="space-y-3">
                  {product.specifications.map((spec, i) => (
                    <div key={`${spec.name}-${i}`}>
                      <dt className="font-semibold">{spec.name}</dt>
                      <dd className="text-muted-foreground">{spec.value}</dd>
                    </div>
                  ))}
                </dl>
              ) : (
                <p className="text-muted-foreground">No specifications available.</p>
              )}
            </TabsContent>

            <TabsContent value="comments" className="pt-6">
              <p className="text-muted-foreground">No comments yet.</p>
            </TabsContent>

            <TabsContent value="files" className="pt-6">
              {product.files?.length ? (
                <ul className="space-y-2">
                  {product.files.map((file, i) => (
                    <li key={`${file.name}-${i}`}>
                      <a
                        href={file.url}
                        download
                        className="text-primary hover:underline"
                      >
                        {file.name}
                      </a>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-muted-foreground">No files available.</p>
              )}
            </TabsContent>

            <TabsContent value="faq" className="pt-6">
              {product.faqs?.length ? (
                <Accordion type="single" collapsible className="w-full">
                  {product.faqs.map((faq, i) => (
                    <AccordionItem key={`${faq.question}-${i}`} value={`faq-${i}`}>
                      <AccordionTrigger>{faq.question}</AccordionTrigger>
                      <AccordionContent>{faq.answer}</AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              ) : (
                <p className="text-muted-foreground">No FAQs available.</p>
              )}
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  )
}

// src/app/product-overview/product-overview.component.ts
import { ProductModel } from '../models/ProductModel';
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { ProductService } from '../services/product.service';
import { CartService } from '../services/cart.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-product-overview',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './product-overview.component.html',
  styleUrls: ['./product-overview.component.css']
})
export class ProductOverviewComponent implements OnInit {

  product: ProductModel | undefined;
  selectedColor: string | undefined;
  selectedSize: any | undefined;
  quantity: number = 1;
  isFavorite: boolean = true;
  selectedImage: string | undefined;
  selectedTab: string = 'details';
  faqs: { question: string, answer: string, open: boolean }[] = [];

  constructor(
    private route: ActivatedRoute,
    private productService: ProductService,
    private cartService: CartService,
    private toastr: ToastrService // Inject ToastrService
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      const id = params['id'];
      this.productService.getProductById(id).subscribe(product => {
        if (product) {
          this.product = product;
          this.selectedImage = product.image;
          if (this.product?.colors && this.product.colors.length > 0) {
            this.selectedColor = this.product.colors[0];
          }
          if (this.product?.sizes && this.product.sizes.length > 0) {
            this.selectedSize = this.product.sizes[0];
          }
          if (this.product?.faqs) {
            this.faqs = this.product.faqs.map(faq => ({ ...faq, open: false }));
          }
          //console.log('Fetched product:', product);
        }
      });
    });
  }

  increaseQuantity(): void {
    this.quantity++;
  }

  decreaseQuantity(): void {
    if (this.quantity > 1) {
      this.quantity--;
    }
  }

  onSubmit(): void {
    if (!this.product) return;

    const orderDetails = {
      productId: this.product.id,
      color: this.selectedColor,
      size: this.selectedSize,
      quantity: this.quantity
    };
  }

  share(): void {
    const url = window.location.href;
    navigator.clipboard.writeText(url).then(() => {
      this.toastr.success('Product URL copied to clipboard!', 'Success');
    }).catch(err => {
      this.toastr.error('Failed to copy URL.', 'Error');
      console.error('Failed to copy URL: ', err);
    });
  }

  selectImage(image: string): void {
    this.selectedImage = image;
  }

  toggleFavorite() {
    this.isFavorite = !this.isFavorite;
  }

  addToCart(): void {
    if (!this.product) {
      this.toastr.error('Product data is missing.', 'Error');
      return;
    }

    if (!this.selectedColor) {
      this.toastr.warning('Please select a color.', 'Warning');
      return;
    }

    if (!this.selectedSize) {
      this.toastr.warning('Please select a size.', 'Warning');
      return;
    }

    if (this.quantity <= 0) {
      this.toastr.warning('Please select a valid quantity.', 'Warning');
      return;
    }

    const cartItem = {
      product: this.product,
      color: this.selectedColor,
      size: this.selectedSize,
      quantity: this.quantity
    };

    this.cartService.addToCart(cartItem);
    this.toastr.success('Product added to cart successfully!', 'Success');
  }

  toggleFaq(index: number): void {
    this.faqs[index].open = !this.faqs[index].open;
  }
}

<section class="ezy__epoverview16 dark py-14 md:py-0 bg-white dark:bg-[#0b1727] text-zinc-900 dark:text-white relative overflow-hidden z-10">
  <div class="container px-4 mx-auto">
    <div class="grid grid-cols-2 gap-6">
      <div class="col-span-2 lg:col-span-1">
        <div class="lg:mr-6">
          <div class="text-center rounded-xl overflow-hidden m-2">
            <img [src]="selectedImage || product?.image" [alt]="product?.title" class="max-w-full max-h-[450px] object-cover h-auto w-full" />
          </div>
          <ul class="flex flex-nowrap gap-3">
            <a *ngFor="let image of product?.images" href="#!" class="rounded-3 overflow-hidden m-2" (click)="selectImage(image); $event.preventDefault()">
              <li>
                <img [src]="image" [alt]="product?.title" [class.border-2]="selectedImage === image" [class.border-blue-600]="selectedImage === image" class="max-w-[120px] object-cover h-auto rounded-xl" />
              </li>
            </a>
          </ul>
        </div>
      </div>
      <div class="col-span-2 lg:col-span-1">
        <div class="mb-6 lg:mb-12">
          <h1 class="text-2xl text-blue-600 leading-none md:text-4xl font-medium mb-4">{{ product?.title }}</h1>
          <p class="opacity-70 mb-6">
            <span class="text-blue-600">{{ product?.rating }}</span>
            <i class="fas fa-star mx-2 text-yellow-500"></i>
            <a href="#!" class="text-blue-600 font-medium ml-1">{{ product?.reviewCount }} Reviews</a>
            <span class="ml-2 text-blue-600">{{ product?.orderCount }} Orders</span>
          </p>
          <h3 class="text-2xl text-blue-600 font-medium"> {{ product?.price | currency:' LKR ' }}</h3>
        </div>
        <form (ngSubmit)="onSubmit()">
          <div class="mb-6">
            <h5 class="font-medium mb-2 text-blue-600">Color</h5>
            <div class="flex flex-wrap gap-2 mb-2">
              <ng-container *ngFor="let color of product?.colors; let i = index">
                <input type="radio" [id]="'color-' + i" name="color" [value]="color" class="absolute hidden" [(ngModel)]="selectedColor" [checked]="i === 0" />
                <label [for]="'color-' + i" [style.background-color]="color" class="w-8 h-8 rounded-full border-2 border-white dark:border-[#0b1727] outline outline-transparent cursor-pointer mt-1" [ngClass]="{'outline-1 outline-yellow-500': selectedColor === color}"></label>
              </ng-container>
            </div>
          </div>
          <div class="mb-6">
            <h5 class="font-medium mb-2">Size: <span class="opacity-50">{{ selectedSize?.name }}</span></h5>
            <div class="flex gap-2 mb-2">
              <ng-container *ngFor="let size of product?.sizes; let i = index">
                <input type="radio" [id]="'size-' + i" name="size" [value]="size" class="absolute hidden" [(ngModel)]="selectedSize" [checked]="i === 0" />
                <label [for]="'size-' + i" class="bg-gray-100 dark:bg-slate-800 cursor-pointer rounded-md flex flex-col overflow-hidden text-start border-2 border-white dark:border-[#0b1727] outline outline-1 px-4 py-3" [ngClass]="{'outline-blue-600': selectedSize === size, 'outline-white dark:outline-[#0b1727] hover:outline-blue-600': selectedSize !== size}">
                  <b class="mb-2">{{ size.name }}</b>
                  <span class="opacity-75 mb-2">{{ size.description }}</span>
                </label>
              </ng-container>
            </div>
          </div>
          <div class="mb-6">
            <h5 class="font-medium mb-2 text-blue-600">QTY</h5>
            <div class="h-11 border dark:border-slate-700 rounded-full flex w-36 relative mt-4 overflow-hidden">
              <button type="button" (click)="decreaseQuantity()" class="w-1/3 pb-1 inline-flex justify-center items-center cursor-pointer text-2xl font-medium border-r dark:border-slate-700 text-blue-600 hover:bg-opacity-20">-</button>
              <input type="number" [(ngModel)]="quantity" name="quantity" class="w-1/3 text-lg font-bold px-2 py-1 text-center bg-transparent text-blue-600 focus:outline-none" />
              <button type="button" (click)="increaseQuantity()" class="w-1/3 pb-1 inline-flex justify-center items-center cursor-pointer text-2xl font-medium border-l dark:border-slate-700 text-blue-600 hover:bg-opacity-10">+</button>
            </div>
          </div>
          <div class="flex items-center my-7">
            <button type="submit" class="bg-blue-600 border border-blue-600 text-white text-sm rounded uppercase cursor-pointer hover:bg-opacity-90 px-10 py-2.5 mr-2">BUY NOW</button>
            <button type="button" (click)="addToCart()" class="border border-blue-600 text-blue-600 hover:bg-blue-600 cursor-pointer hover:text-white text-sm rounded uppercase px-6 py-2.5 mr-2">Add to cart</button>
            <button type="button" (click)="toggleFavorite()" class=" hover:transform hover:scale-120 text-blue-600 mr-2 px-3 py-2 text-lg font-bold">
              <i class="far" [ngClass]="{'fa-heart': !isFavorite, 'fas fa-heart': isFavorite}"></i>
            </button>
            <button type="button" (click)="share()" class=" rounded cursor-pointer hover:transform hover:scale-120 text-blue-600 mr-2 px-3 py-2 text-lg font-bold">
              <i class="fas fa-share-alt mr-1 text-sm"></i>
            </button>
          </div>
          <p class="opacity-70 lg:mr-56 xl:mr-80 text-blue-600">{{ product?.description }}</p>
        </form>
      </div>
    </div>
  </div>
</section>


<!-- Collapsible Section with Tabs -->
<section class="mt-10">
  <div class="container mx-auto">
    <div class="bg-white dark:bg-[#0b1727] rounded-lg shadow-lg">
      <div class="flex justify-around border-b dark:border-gray-700">
        <button (click)="selectedTab = 'specifications'" [ngClass]="{'border-b-2 border-blue-600': selectedTab === 'specifications'}" class="py-4 px-6 text-blue-600">Specifications</button>
        <button (click)="selectedTab = 'comments'" [ngClass]="{'border-b-2 border-blue-600': selectedTab === 'comments'}" class="py-4 px-6 text-blue-600">Comments</button>
        <button (click)="selectedTab = 'files'" [ngClass]="{'border-b-2 border-blue-600': selectedTab === 'files'}" class="py-4 px-6 text-blue-600">Files</button>
        <button (click)="selectedTab = 'faq'" [ngClass]="{'border-b-2 border-blue-600': selectedTab === 'faq'}" class="py-4 px-6 text-blue-600">FAQ</button>
      </div>
      <div class="p-6">
        <div *ngIf="selectedTab === 'comments'">
          <h2 class="text-xl font-semibold mb-4">Comments</h2>
          <!-- Add comments section here -->
        </div>
        <div *ngIf="selectedTab === 'files'">
          <h2 class="text-xl font-semibold mb-4">Files</h2>
          <div class="space-y-4">
            <div *ngFor="let file of product?.files">
              <a [href]="file.url" download class="text-blue-600 hover:underline">{{ file.name }}</a>
            </div>
          </div>
        </div>
        <div *ngIf="selectedTab === 'specifications'">
          <h2 class="text-xl font-semibold mb-4">Specifications</h2>
          <ul>
            <li *ngFor="let spec of product?.specifications">
              <strong>{{ spec.name }}:</strong> {{ spec.value }}
            </li>
          </ul>
        </div>
        <div *ngIf="selectedTab === 'faq'">
          <div class="container px-16 md:px-8 lg:px-28">
            <div class="col-span-12 md:col-span-6">
              <div *ngFor="let faq of faqs; let i = index" class="shadow dark:shadow-none dark:bg-[#1E2735] rounded-lg mt-6">
                <a class="btn p-4 lg:p-6 w-full text-start flex justify-between items-center cursor-pointer" (click)="toggleFaq(i)">
                  <span>{{ faq.question }}</span>
                  <span class="fas" [ngClass]="{'fa-chevron-up': faq.open, 'fa-chevron-down': !faq.open}"></span>
                </a>
                <div class="ezy__faq1-content p-4 lg:p-6 pt-0" [ngClass]="{'hidden': !faq.open}">
                  <p class="opacity-50">{{ faq.answer }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
