// src/app/home/home.component.ts

import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Banner } from '../models/BannerModel';
import { HomeService } from '../services/home.service';
import { FeaturedProduct } from '../models/FeaturedProducts';
import { Catergory } from '../models/CatergoryModel';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit, OnDestroy {
  currentIndex = 0;
  currentBannerIndex = 0;
  private autoScrollInterval: any;
  banners: Banner[] = [];
  featuredProducts: FeaturedProduct[] = [];
  categories: Catergory[] = [];

  constructor(private homeService: HomeService) { }


  ngOnInit() {
    this.homeService.getBanners().subscribe(data => {
      //console.log('Banners fetched:', data);
      this.banners = data || [];  // Fallback to an empty array if data is null/undefined
    });
    this.homeService.getFeaturedProducts().subscribe(data => {
      this.featuredProducts = data || [];  // Fallback to an empty array if data is null/undefined
      console.log('FeaturedProducts:', this.featuredProducts);
    });
    this.homeService.getCategories().subscribe(data => {
      this.categories = data || [];  // Fallback to an empty array if data is null/undefined
      //console.log('Catergories:', this.categories);
    });


    this.startAutoScroll();
  }

  ngOnDestroy() {
    this.stopAutoScroll();
  }

  private startAutoScroll() {
    this.autoScrollInterval = setInterval(() => {
      this.currentIndex = (this.currentIndex + 1) % this.featuredProducts.length;
      this.nextBanner();
    }, 5000); // Scroll every 2 minutes
  }

  private stopAutoScroll() {
    if (this.autoScrollInterval) {
      clearInterval(this.autoScrollInterval);
    }
  }

  nextBanner() {
    this.currentBannerIndex = (this.currentBannerIndex + 1) % this.banners.length;
  }

  prevBanner() {
    this.currentBannerIndex = (this.currentBannerIndex - 1 + this.banners.length) % this.banners.length;
  }

  selectBanner(index: number) {
    this.currentBannerIndex = index;
  }

  // Reset timer when manually changing slides
  onManualChange() {
    this.stopAutoScroll();
    this.startAutoScroll();
  }

  onMouseEnter() {
    this.stopAutoScroll();
  }

  onMouseLeave() {
    this.startAutoScroll();
  }
}

<!-- Hero Banner -->
<div class="banner" (mouseenter)="onMouseEnter()" (mouseleave)="onMouseLeave()">
  <div class="banner__layout">
    @for (banner of banners; track banner.id; let i = $index) {
      <div
        class="banner__image-container"
        [style.opacity]="i === currentBannerIndex ? 1 : 0"
        [style.visibility]="i === currentBannerIndex ? 'visible' : 'hidden'"
        [style.position]="i === currentBannerIndex ? 'relative' : 'absolute'"
      >
        <figure
          class="banner__figure"
          [style.backgroundImage]="'url(' + banner.image + ')'"
          [class]="banner.backgroundColor"
        ></figure>

        <div class="banner__content">
          <h2>{{ banner.title }}</h2>
          <p>{{ banner.subtitle }}</p>
          <a [routerLink]="[banner.buttonLink]" class="banner__link">
            <i>{{ banner.buttonText }}</i>
          </a>
        </div>
      </div>
    }

    <!-- Navigation Controls -->
    <button
      class="banner__nav banner__nav--prev"
      (click)="prevBanner(); onManualChange()"
      aria-label="Previous slide"
    >
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
      </svg>
    </button>

    <button
      class="banner__nav banner__nav--next"
      (click)="nextBanner(); onManualChange()"
      aria-label="Next slide"
    >
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
      </svg>
    </button>

    <!-- Dots Navigation -->
    <div class="banner__dots">
      @for (banner of banners; track banner.id; let i = $index) {
        <button
          class="banner__dot"
          [class.banner__dot--active]="i === currentBannerIndex"
          (click)="selectBanner(i); onManualChange()"
          [attr.aria-label]="'Go to slide ' + (i + 1)"
        ></button>
      }
    </div>
  </div>
</div>

<!-- Categories Overview -->
<section class="categories-overview py-16 bg-gray-50">
  <div class="container mx-auto px-4">
    <h2 class="text-3xl font-bold mb-8 text-center">Shop by Category</h2>
    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
      <a [routerLink]="['/category/laptops']" class="category-item group">
        <div class="bg-white p-6 rounded-lg shadow-md transition-all duration-300 hover:shadow-xl text-center">
          <i class="fas fa-laptop text-4xl text-blue-600 mb-4"></i>
          <h3 class="text-lg font-semibold">Laptops</h3>
          <span class="text-sm text-gray-500">Starting from $699</span>
        </div>
      </a>
      <a [routerLink]="['/category/processors']" class="category-item group">
        <div class="bg-white p-6 rounded-lg shadow-md transition-all duration-300 hover:shadow-xl text-center">
          <i class="fas fa-microchip text-4xl text-blue-600 mb-4"></i>
          <h3 class="text-lg font-semibold">Processors</h3>
          <span class="text-sm text-gray-500">Starting from $199</span>
        </div>
      </a>
      <a [routerLink]="['/category/graphics-cards']" class="category-item group">
        <div class="bg-white p-6 rounded-lg shadow-md transition-all duration-300 hover:shadow-xl text-center">
          <i class="fas fa-tv text-4xl text-blue-600 mb-4"></i>
          <h3 class="text-lg font-semibold">Graphics Cards</h3>
          <span class="text-sm text-gray-500">Starting from $299</span>
        </div>
      </a>
      <a [routerLink]="['/category/accessories']" class="category-item group">
        <div class="bg-white p-6 rounded-lg shadow-md transition-all duration-300 hover:shadow-xl text-center">
          <i class="fas fa-keyboard text-4xl text-blue-600 mb-4"></i>
          <h3 class="text-lg font-semibold">Accessories</h3>
          <span class="text-sm text-gray-500">Starting from $29</span>
        </div>
      </a>
    </div>
  </div>
</section>

<!-- Featured Products -->
<section
  class="featured-products py-16"
  (mouseenter)="onMouseEnter()"
  (mouseleave)="onMouseLeave()"
>
  <div class="container mx-auto px-4">
    <h2 class="text-3xl font-bold mb-8">Featured Products</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
      @for (product of visibleProducts; track product.id) {
        <div class="product-card bg-white shadow-lg rounded-lg overflow-hidden transform transition duration-300 hover:scale-105">
          <div class="relative">
            <img [src]="product.image" [alt]="product.name" class="w-full h-64 object-cover">
            @if (product.badge) {
              <span class="absolute top-4 right-4 {{product.badge.color}} text-white px-2 py-1 rounded">
                {{product.badge.text}}
              </span>
            }
          </div>
          <div class="p-6">
            <h3 class="text-xl font-semibold mb-2">{{product.name}}</h3>
            <p class="text-gray-600 mb-4">{{product.description}}</p>
            <div class="flex justify-between items-center">
              <div>
                <span class="text-2xl font-bold text-blue-600">${{product.price}}</span>
                @if (product.oldPrice) {
                  <span class="text-sm text-gray-500 line-through ml-2">${{product.oldPrice}}</span>
                }
              </div>
              <a [routerLink]="['/category/product', product.id]" class="bg-blue-600 text-white py-2 px-4 rounded hover:bg-blue-700 transition duration-300">
                Learn More
              </a>
            </div>
          </div>
        </div>
      }
    </div>
  </div>
</section>

<!-- Why Choose Us -->
<section class="why-choose-us py-16 bg-gray-50">
  <div class="container mx-auto px-4">
    <h2 class="text-3xl font-bold mb-12 text-center">Why Choose Us</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
      <div class="feature-card text-center">
        <div class="inline-block p-4 bg-blue-100 rounded-full mb-4">
          <i class="fas fa-shipping-fast text-3xl text-blue-600"></i>
        </div>
        <h3 class="text-xl font-semibold mb-2">Fast Shipping</h3>
        <p class="text-gray-600">Free delivery for orders over $500</p>
      </div>
      <div class="feature-card text-center">
        <div class="inline-block p-4 bg-blue-100 rounded-full mb-4">
          <i class="fas fa-shield-alt text-3xl text-blue-600"></i>
        </div>
        <h3 class="text-xl font-semibold mb-2">Secure Payments</h3>
        <p class="text-gray-600">100% secure payment methods</p>
      </div>
      <div class="feature-card text-center">
        <div class="inline-block p-4 bg-blue-100 rounded-full mb-4">
          <i class="fas fa-headset text-3xl text-blue-600"></i>
        </div>
        <h3 class="text-xl font-semibold mb-2">24/7 Support</h3>
        <p class="text-gray-600">Dedicated support anytime</p>
      </div>
      <div class="feature-card text-center">
        <div class="inline-block p-4 bg-blue-100 rounded-full mb-4">
          <i class="fas fa-undo text-3xl text-blue-600"></i>
        </div>
        <h3 class="text-xl font-semibold mb-2">Easy Returns</h3>
        <p class="text-gray-600">30-day return policy</p>
      </div>
    </div>
  </div>
</section>

<!-- Newsletter -->
<section class="newsletter py-16 bg-blue-600 text-white">
  <div class="container mx-auto px-4 text-center">
    <h2 class="text-3xl font-bold mb-4">Stay Updated</h2>
    <p class="mb-8 text-blue-100">Subscribe to our newsletter for the latest products and exclusive offers</p>
    <form class="max-w-md mx-auto flex gap-4">
      <input type="email" placeholder="Enter your email" class="flex-1 px-4 py-2 rounded text-gray-900 dark:text-white bg-white dark:bg-gray-800 border border-blue-300 dark:text-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent transition duration-300 placeholder-blue-600 dark:placeholder-blue-200">
      <button type="submit" class="bg-white text-blue-600 px-6 py-2 rounded font-semibold hover:bg-blue-50 transition duration-300">
        Subscribe
      </button>
    </form>
  </div>
</section>

// src/pages/Home.tsx
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ChevronLeft, ChevronRight, Headset, RotateCcw, ShieldCheck, Truck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Skeleton } from '@/components/ui/skeleton'
import { ProductImage } from '@/components/ProductImage'
import { getBanners, getCategories, getFeaturedProducts } from '@/lib/api'
import { formatLKR } from '@/lib/format'
import { iconFromFaClass } from '@/lib/icons'
import { useAsync } from '@/hooks/useAsync'
import { cn } from '@/lib/utils'

const AUTO_SCROLL_MS = 5000

/**
 * banner.json / featuredProducts.json ship Tailwind class strings. Tailwind only
 * emits classes it can see in source, so map the data values onto literal classes.
 */
const BANNER_GRADIENTS: Record<string, string> = {
  'bg-gradient-to-r from-purple-900 to-indigo-800': 'bg-linear-to-r from-purple-900 to-indigo-800',
  'bg-gradient-to-r from-green-900 to-emerald-800': 'bg-linear-to-r from-green-900 to-emerald-800',
  'bg-gradient-to-r from-blue-900 to-cyan-800': 'bg-linear-to-r from-blue-900 to-cyan-800',
  'bg-gradient-to-r from-red-900 to-orange-800': 'bg-linear-to-r from-red-900 to-orange-800',
  'bg-gradient-to-r from-yellow-900 to-amber-800': 'bg-linear-to-r from-yellow-900 to-amber-800',
}

const BADGE_COLORS: Record<string, string> = {
  'bg-red-500': 'bg-red-500',
  'bg-green-500': 'bg-green-500',
  'bg-purple-500': 'bg-purple-500',
  'bg-yellow-500': 'bg-yellow-500',
}

const WHY_CHOOSE_US = [
  { icon: Truck, title: 'Fast Shipping', copy: 'Free delivery for orders over $500' },
  { icon: ShieldCheck, title: 'Secure Payments', copy: '100% secure payment methods' },
  { icon: Headset, title: '24/7 Support', copy: 'Dedicated support anytime' },
  { icon: RotateCcw, title: 'Easy Returns', copy: '30-day return policy' },
]

function HeroBanner() {
  const { data: banners = [], loading } = useAsync(getBanners, [])
  const [index, setIndex] = useState(0)
  const [paused, setPaused] = useState(false)

  const next = useCallback(() => {
    setIndex((i) => (banners.length ? (i + 1) % banners.length : 0))
  }, [banners.length])

  const prev = () => {
    setIndex((i) => (banners.length ? (i - 1 + banners.length) % banners.length : 0))
  }

  useEffect(() => {
    if (paused || banners.length <= 1) return
    const id = setInterval(next, AUTO_SCROLL_MS)
    return () => clearInterval(id)
  }, [paused, banners.length, next])

  if (loading) {
    return <Skeleton className="h-[60vh] w-full rounded-xl" />
  }
  if (banners.length === 0) return null

  const current = banners[index]

  return (
    <section
      aria-roledescription="carousel"
      aria-label="Featured promotions"
      className="bg-card relative overflow-hidden rounded-xl border"
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
    >
      <div className="flex flex-col lg:h-[60vh] lg:min-h-[420px] lg:flex-row">
        <div
          className={cn(
            'relative h-64 w-full overflow-hidden lg:h-auto lg:w-3/5',
            BANNER_GRADIENTS[current.backgroundColor] ?? 'bg-muted',
          )}
        >
          <img
            key={current.image}
            src={current.image}
            alt=""
            className="size-full object-cover transition-transform duration-700 hover:scale-105"
          />
          <Button
            variant="secondary"
            size="icon"
            onClick={prev}
            aria-label="Previous slide"
            className="absolute top-1/2 left-4 -translate-y-1/2 rounded-full opacity-90"
          >
            <ChevronLeft />
          </Button>
          <Button
            variant="secondary"
            size="icon"
            onClick={next}
            aria-label="Next slide"
            className="absolute top-1/2 right-4 -translate-y-1/2 rounded-full opacity-90"
          >
            <ChevronRight />
          </Button>
        </div>

        <div className="flex w-full flex-col justify-center gap-4 p-8 text-center lg:w-2/5 lg:p-12 lg:text-left">
          {current.title && (
            <h2 className="text-4xl leading-tight font-bold lg:text-5xl">{current.title}</h2>
          )}
          {current.subtitle && (
            <p className="text-muted-foreground text-lg lg:text-xl">{current.subtitle}</p>
          )}
          {current.buttonLink && (
            <div>
              <Button asChild size="lg" variant="outline" className="mt-2">
                <Link
                  to={{
                    pathname: current.buttonLink,
                    search: current.category ? `?category=${encodeURIComponent(current.category)}` : '',
                  }}
                >
                  {current.buttonText}
                </Link>
              </Button>
            </div>
          )}

          <div className="mt-4 flex justify-center gap-2 lg:justify-start">
            {banners.map((_, i) => (
              <button
                key={i}
                type="button"
                onClick={() => setIndex(i)}
                aria-label={`Go to slide ${i + 1}`}
                aria-current={i === index}
                className={cn(
                  'border-primary size-3 rounded-full border-2 transition-colors',
                  i === index ? 'bg-primary' : 'bg-transparent',
                )}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}

function CategoriesOverview() {
  const { data: categories = [] } = useAsync(getCategories, [])

  return (
    <section className="py-16">
      <h2 className="mb-8 text-center text-3xl font-bold">Shop by Featured Categories</h2>
      <div className="grid grid-cols-2 gap-6 md:grid-cols-3 lg:grid-cols-4">
        {categories.map((category) => {
          const Icon = iconFromFaClass(category.icon)
          return (
            <Link key={category.id} to={`/product-grid?category=${encodeURIComponent(category.slug)}`}>
              <Card className="h-full text-center transition-shadow hover:shadow-xl">
                <CardContent className="flex flex-col items-center gap-2">
                  <Icon className="text-primary size-9" aria-hidden="true" />
                  <h3 className="text-lg font-semibold">{category.name}</h3>
                  <span className="text-muted-foreground text-sm">
                    Starting from {formatLKR(category.startingPrice)}
                  </span>
                </CardContent>
              </Card>
            </Link>
          )
        })}
      </div>
    </section>
  )
}

function FeaturedProducts() {
  const { data: products = [] } = useAsync(getFeaturedProducts, [])

  return (
    <section className="py-16">
      <h2 className="mb-8 text-3xl font-bold">Featured Products</h2>
      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
        {products.map((product) => (
          <Card key={product.id} className="group overflow-hidden pt-0 transition-shadow hover:shadow-xl">
            <div className="relative overflow-hidden">
              <ProductImage
                src={product.image}
                alt={product.name}
                className="h-64 w-full object-cover transition-transform duration-300 group-hover:scale-105"
              />
              {product.badge && (
                <span
                  className={cn(
                    'absolute top-4 right-4 rounded px-2 py-1 text-sm font-medium text-white',
                    BADGE_COLORS[product.badge.color] ?? 'bg-primary',
                  )}
                >
                  {product.badge.text}
                </span>
              )}
            </div>
            <CardContent>
              <h3 className="group-hover:text-primary mb-2 line-clamp-2 text-xl font-semibold transition-colors">
                {product.name}
              </h3>
              <p className="text-muted-foreground mb-4 line-clamp-2">{product.description}</p>
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <span className="text-primary text-2xl font-bold">{formatLKR(product.price)}</span>
                  {product.oldPrice && (
                    <span className="text-muted-foreground ml-2 text-sm line-through">
                      {formatLKR(product.oldPrice)}
                    </span>
                  )}
                </div>
                <Button asChild>
                  <Link to={`/product-overview/${product.productId}`}>Learn More</Link>
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  )
}

export default function Home() {
  return (
    <div>
      <HeroBanner />
      <CategoriesOverview />
      <FeaturedProducts />

      <section className="py-16">
        <h2 className="mb-12 text-center text-3xl font-bold">Why Choose Us</h2>
        <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
          {WHY_CHOOSE_US.map(({ icon: Icon, title, copy }) => (
            <div key={title} className="text-center">
              <div className="bg-primary/10 mb-4 inline-flex rounded-full p-4">
                <Icon className="text-primary size-8" aria-hidden="true" />
              </div>
              <h3 className="mb-2 text-xl font-semibold">{title}</h3>
              <p className="text-muted-foreground">{copy}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="bg-primary text-primary-foreground rounded-xl px-4 py-16 text-center">
        <h2 className="mb-4 text-3xl font-bold">Stay Updated</h2>
        <p className="mb-8 opacity-90">
          Subscribe to our newsletter for the latest products and exclusive offers
        </p>
        <form
          className="mx-auto flex max-w-md gap-4"
          onSubmit={(event) => event.preventDefault()}
        >
          <Input
            type="email"
            required
            placeholder="Enter your email"
            aria-label="Email address"
            className="bg-background text-foreground flex-1"
          />
          <Button type="submit" variant="secondary">
            Subscribe
          </Button>
        </form>
      </section>
    </div>
  )
}
