// src/app/support/support.component.ts
import { Component } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormControl } from '@angular/forms';
@Component({
  selector: 'app-support',
  imports: [ReactiveFormsModule],
  templateUrl: './support.component.html',
  styleUrl: './support.component.css'
})
export class SupportComponent {
onSubmit() {
throw new Error('Method not implemented.');
}
contactForm: any;

}

<section
  class="ezy__contact7 light py-0 md:py-1 bg-white dark:bg-[#0b1727] text-zinc-900 dark:text-white overflow-hidden">
  <div class="container px-4">
    <div class="grid grid-cols-12 py-6">
      <div class="col-span-12 lg:col-span-6 lg:col-start-7 order-2 mb-4 lg:mb-0">
        <div class="bg-center bg-no-repeat bg-cover min-h[150px] w-full lg:w-[50vw] h-full" style="
        background-image: url('https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1472&q=80');
          "></div>
      </div>

      <div class="col-span-12 lg:col-span-5">
        <div class="">
          <div class="p-6 md:p-12">
            <h2 class="text-6xl leading-none md:text-[45px] font-bold mb-4 text-black">
              Technical Support
            </h2>
            <p class="text-xl mb-12 text-black">
              Get help with your technical issues. We're here to assist you.
            </p>
            <form [formGroup]="contactForm" (ngSubmit)="onSubmit()" class="bg-white p-8 shadow-lg rounded-xl">
              <div class="mb-5">
                <input type="text" formControlName="name"
                  class="h-[56px] border border-gray-300 rounded-xl focus:border-blue-500 focus:ring-2 focus:ring-blue-500 w-full px-6 py-4 bg-white text-gray-900 placeholder-gray-500 text-lg"
                  placeholder="Full Name" />
              </div>
              <div class="mb-5">
                <input type="email" formControlName="email"
                  class="h-[56px] border border-gray-300 rounded-xl focus:border-blue-500 focus:ring-2 focus:ring-blue-500 w-full px-6 py-4 bg-white text-gray-900 placeholder-gray-500 text-lg"
                  placeholder="Email Address" />
              </div>
              <div class="mb-5">
                <select formControlName="issueType"
                  class="h-[56px] border border-gray-300 rounded-xl focus:border-blue-500 focus:ring-2 focus:ring-blue-500 w-full px-6 py-4 bg-white text-gray-900 text-lg">
                  <option value="">Select Issue Type</option>
                  <option value="hardware">Hardware Problem</option>
                  <option value="software">Software Issue</option>
                  <option value="network">Network Connection</option>
                  <option value="other">Other</option>
                </select>
              </div>
              <div class="mb-5">
                <input type="text" formControlName="productModel"
                  class="h-[56px] border border-gray-300 rounded-xl focus:border-blue-500 focus:ring-2 focus:ring-blue-500 w-full px-6 py-4 bg-white text-gray-900 placeholder-gray-500 text-lg"
                  placeholder="Product Model Number" />
              </div>
              <div class="mb-5">
                <select formControlName="priority"
                  class="h-[56px] border border-gray-300 rounded-xl focus:border-blue-500 focus:ring-2 focus:ring-blue-500 w-full px-6 py-4 bg-white text-gray-900 text-lg">
                  <option value="">Select Priority Level</option>
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                  <option value="critical">Critical</option>
                </select>
              </div>
              <div class="mb-5">
                <textarea formControlName="description"
                  class="border border-gray-300 rounded-xl focus:border-blue-500 focus:ring-2 focus:ring-blue-500 w-full px-6 py-4 bg-white text-gray-900 placeholder-gray-500 text-lg"
                  placeholder="Detailed Description of the Issue" rows="4"></textarea>
              </div>
              <div class="mb-5">
                <label class="block text-gray-700 mb-2">Upload Screenshots</label>
                <input type="file" formControlName="screenshots" multiple accept="image/*"
                  class="w-full border border-gray-300 rounded-xl p-2" />
              </div>
              <div class="mb-5">
                <label class="block text-gray-700 mb-2">Upload Related Documents</label>
                <input type="file" formControlName="documents" multiple accept=".pdf,.doc,.docx"
                  class="w-full border border-gray-300 rounded-xl p-2" />
              </div>
              <div class="text-end">
                <button type="submit"
                  class="bg-blue-600 hover:bg-blue-500 text-white px-10 py-4 rounded-xl shadow-md transition-all duration-300 text-lg">
                  Submit Ticket
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

// src/pages/Support.tsx
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'

const ISSUE_TYPES = [
  { value: 'hardware', label: 'Hardware Problem' },
  { value: 'software', label: 'Software Issue' },
  { value: 'network', label: 'Network Connection' },
  { value: 'other', label: 'Other' },
]

const PRIORITIES = [
  { value: 'low', label: 'Low' },
  { value: 'medium', label: 'Medium' },
  { value: 'high', label: 'High' },
  { value: 'critical', label: 'Critical' },
]

const supportSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  email: z.string().min(1, 'Email is required').email('Valid email is required'),
  issueType: z.string().min(1, 'Please select an issue type'),
  productModel: z.string().min(1, 'Product model is required'),
  priority: z.string().min(1, 'Please select a priority level'),
  description: z.string().min(1, 'Description is required'),
})

type SupportValues = z.infer<typeof supportSchema>

export default function Support() {
  const form = useForm<SupportValues>({
    resolver: zodResolver(supportSchema),
    defaultValues: {
      name: '',
      email: '',
      issueType: '',
      productModel: '',
      priority: '',
      description: '',
    },
  })

  const onSubmit = (values: SupportValues) => {
    console.info('Support ticket submitted', values)
    toast.success('Your ticket has been submitted. We’ll be in touch shortly.')
    form.reset()
  }

  return (
    <div className="grid items-start gap-8 py-6 lg:grid-cols-2">
      <div className="order-2 hidden lg:block">
        <img
          src="https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1472&q=80"
          alt=""
          className="sticky top-24 h-[600px] w-full rounded-2xl object-cover"
        />
      </div>

      <div className="order-1">
        <h1 className="mb-4 text-4xl leading-none font-bold md:text-5xl">Technical Support</h1>
        <p className="text-muted-foreground mb-8 text-xl">
          Get help with your technical issues. We&apos;re here to assist you.
        </p>

        <Card>
          <CardContent>
            <Form {...form}>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5">
                <FormField
                  control={form.control}
                  name="name"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Full Name</FormLabel>
                      <FormControl>
                        <Input placeholder="Full Name" autoComplete="name" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="email"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Email Address</FormLabel>
                      <FormControl>
                        <Input
                          type="email"
                          placeholder="Email Address"
                          autoComplete="email"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="issueType"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Issue Type</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger className="w-full">
                            <SelectValue placeholder="Select Issue Type" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {ISSUE_TYPES.map((option) => (
                            <SelectItem key={option.value} value={option.value}>
                              {option.label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="productModel"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Product Model Number</FormLabel>
                      <FormControl>
                        <Input placeholder="Product Model Number" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="priority"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Priority Level</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger className="w-full">
                            <SelectValue placeholder="Select Priority Level" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {PRIORITIES.map((option) => (
                            <SelectItem key={option.value} value={option.value}>
                              {option.label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="description"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Description</FormLabel>
                      <FormControl>
                        <Textarea
                          rows={4}
                          placeholder="Detailed Description of the Issue"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-2">
                    <FormLabel htmlFor="screenshots">Upload Screenshots</FormLabel>
                    <Input id="screenshots" type="file" multiple accept="image/*" />
                  </div>
                  <div className="space-y-2">
                    <FormLabel htmlFor="documents">Upload Related Documents</FormLabel>
                    <Input id="documents" type="file" multiple accept=".pdf,.doc,.docx" />
                  </div>
                </div>

                <div className="text-right">
                  <Button type="submit" size="lg">
                    Submit Ticket
                  </Button>
                </div>
              </form>
            </Form>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
